`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_CK_087.title -d '[{ "locale": "en_US","text": "Cook multiple dishes at the same time","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_CK_087.shortText -d '[{ "locale": "en_US","text": "Cook multiple dishes at the same time. Be strategic with your oven racks. You\u0027ll save time and energy!","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_CK_087.longText -d '[{ "locale": "en_US","text": "Cook multiple dishes at the same time. Be strategic with your oven racks. You\u0027ll save time and energy!","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_EDU_G_CK_002.insightText -d '[{ "locale": "en_US","text": "An average U.S. home with a gas stove spends about 5% of its gas bill on cooking.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_CK_088.title -d '[{ "locale": "en_US","text": "Use the self-cleaning feature wisely","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_CK_088.shortText -d '[{ "locale": "en_US","text": "The self-cleaning feature on your oven uses less energy if turned on right after cooking a meal.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_CK_088.longText -d '[{ "locale": "en_US","text": "The self-cleaning feature on your oven uses less energy if turned on right after cooking a meal.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_EDU_G_CK_002.insightText -d '[{ "locale": "en_US","text": "An average U.S. home with a gas stove spends about 5% of its gas bill on cooking.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_CK_089.title -d '[{ "locale": "en_US","text": "Use the right size burners and pots","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_CK_089.shortText -d '[{ "locale": "en_US","text": "Using the right size burners for your pots can speed up your cooking & reduce energy loss.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_CK_089.longText -d '[{ "locale": "en_US","text": "Using the right size burners for your pots can speed up your cooking & reduce energy loss.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_EDU_G_CK_002.insightText -d '[{ "locale": "en_US","text": "An average U.S. home with a gas stove spends about 5% of its gas bill on cooking.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_CK_091.title -d '[{ "locale": "en_US","text": "Turn off oven earlier","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_CK_091.shortText -d '[{ "locale": "en_US","text": "You can turn off the oven a few minutes early. The oven will remain hot enough to complete the job.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_CK_091.longText -d '[{ "locale": "en_US","text": "You can turn off the oven a few minutes early. The oven will remain hot enough to complete the job.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_EDU_G_CK_002.insightText -d '[{ "locale": "en_US","text": "An average U.S. home with a gas stove spends about 5% of its gas bill on cooking.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_CK_094.title -d '[{ "locale": "en_US","text": "Use the right size appliance to heat food","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_CK_094.shortText -d '[{ "locale": "en_US","text": "Use the right size appliance to heat food. A toaster or convection oven uses one-third to one-half as much energy as a full-sized oven.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_CK_094.longText -d '[{ "locale": "en_US","text": "Use the right size appliance to heat food. A toaster or convection oven uses one-third to one-half as much energy as a full-sized oven.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_EDU_G_CK_002.insightText -d '[{ "locale": "en_US","text": "An average U.S. home with a gas stove spends about 5% of its gas bill on cooking.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_CK_096.title -d '[{ "locale": "en_US","text": "Consider replacing your old cookware","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_CK_096.shortText -d '[{ "locale": "en_US","text": "Consider replacing your old cookware. Flat-bottomed cookware maximizes contact with heating elements. Replace if bottom is warped.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_CK_096.longText -d '[{ "locale": "en_US","text": "Consider replacing your old cookware. Flat-bottomed cookware maximizes contact with heating elements. Replace if bottom is warped.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_EDU_G_CK_002.insightText -d '[{ "locale": "en_US","text": "An average U.S. home with a gas stove spends about 5% of its gas bill on cooking.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_CK_097.title -d '[{ "locale": "en_US","text": "Your cookware matters","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_CK_097.shortText -d '[{ "locale": "en_US","text": "Your cookware matters. Cookware with flat bottoms, straight sides, and tight-fitting lids help reduce cooking time.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_CK_097.longText -d '[{ "locale": "en_US","text": "Your cookware matters. Cookware with flat bottoms, straight sides, and tight-fitting lids help reduce cooking time.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_EDU_G_CK_002.insightText -d '[{ "locale": "en_US","text": "An average U.S. home with a gas stove spends about 5% of its gas bill on cooking.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_CK_099.title -d '[{ "locale": "en_US","text": "Use oven lights to check on food","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_CK_099.shortText -d '[{ "locale": "en_US","text": "Use the oven light to look through the glass window instead of opening it to check on food.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_CK_099.longText -d '[{ "locale": "en_US","text": "Use the oven light to look through the glass window instead of opening it to check on food.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_EDU_G_CK_002.insightText -d '[{ "locale": "en_US","text": "An average U.S. home with a gas stove spends about 5% of its gas bill on cooking.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_CK_101.title -d '[{ "locale": "en_US","text": "Use metal baking dishes","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_CK_101.shortText -d '[{ "locale": "en_US","text": "Use metal baking dishes. They transfer heat better to the cooked food compared to glass or stoneware.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_CK_101.longText -d '[{ "locale": "en_US","text": "Use metal baking dishes. They transfer heat better to the cooked food compared to glass or stoneware.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_EDU_G_CK_002.insightText -d '[{ "locale": "en_US","text": "An average U.S. home with a gas stove spends about 5% of its gas bill on cooking.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_CK_102.title -d '[{ "locale": "en_US","text": "Clean around your burners","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_CK_102.shortText -d '[{ "locale": "en_US","text": "Clean around your burners. Remove residual material from burners in order to minimize energy waste.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_CK_102.longText -d '[{ "locale": "en_US","text": "Clean around your burners. Remove residual material from burners in order to minimize energy waste.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_EDU_G_CK_002.insightText -d '[{ "locale": "en_US","text": "An average U.S. home with a gas stove spends about 5% of its gas bill on cooking.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_019.title -d '[{ "locale": "en_US","text": "Find the magic number on the thermostat","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_019.shortText -d '[{ "locale": "en_US","text": "Find the magic number on the thermostat. For every degree lower you set your thermostat, you save about 3% on heating costs.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_019.longText -d '[{ "locale": "en_US","text": "Find the magic number on the thermostat. For every degree lower you set your thermostat, you save about 3% on heating costs.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_EDU_G_SH_003.insightText -d '[{ "locale": "en_US","text": "Did you know? Almost half of the U.S. population with a heating system sets one temperature and leave it there most of the time?","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_213.title -d '[{ "locale": "en_US","text": "Install DIY low-cost storm windows","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_213.shortText -d '[{ "locale": "en_US","text": "Install DIY window seal kits to save energy and increase comfort.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_213.longText -d '[{ "locale": "en_US","text": "Install DIY window seal kits to save energy and increase comfort.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_SLF_G_SH_001.insightText -d '[{ "locale": "en_US","text": "You spent ${Value}% of your bill on heating, during the last billing cycle. That\u0027s higher than the average user!","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_215.title -d '[{ "locale": "en_US","text": "Remove or retract awnings in winter","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_215.shortText -d '[{ "locale": "en_US","text": "Take down or retract any awnings over your windows to let in winter sunshine.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_215.longText -d '[{ "locale": "en_US","text": "Take down or retract any awnings over your windows to let in winter sunshine.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_SLF_G_SH_001.insightText -d '[{ "locale": "en_US","text": "You spent ${Value}% of your bill on heating, during the last billing cycle. That\u0027s higher than the average user!","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_216.title -d '[{ "locale": "en_US","text": "Install fiberglass weather-stripping","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_216.shortText -d '[{ "locale": "en_US","text": "Install fiberglass weather-stripping. It can help seal off a common area of energy leakage.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_216.longText -d '[{ "locale": "en_US","text": "Install fiberglass weather-stripping. It can help seal off a common area of energy leakage.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_SLF_G_SH_001.insightText -d '[{ "locale": "en_US","text": "You spent ${Value}% of your bill on heating, during the last billing cycle. That\u0027s higher than the average user!","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_217.title -d '[{ "locale": "en_US","text": "Seal with fire-resistant materials","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_217.shortText -d '[{ "locale": "en_US","text": "Seal air leaks with fire-resistant materials like caulk and/or foam sealant.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_217.longText -d '[{ "locale": "en_US","text": "Seal air leaks with fire-resistant materials like caulk and/or foam sealant.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_SLF_G_SH_001.insightText -d '[{ "locale": "en_US","text": "You spent ${Value}% of your bill on heating, during the last billing cycle. That\u0027s higher than the average user!","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_218.title -d '[{ "locale": "en_US","text": "Replace old windows","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_218.shortText -d '[{ "locale": "en_US","text": "Consider upgrading to Energy Star-certified windows.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_218.longText -d '[{ "locale": "en_US","text": "Consider upgrading to Energy Star-certified windows.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_SLF_G_SH_001.insightText -d '[{ "locale": "en_US","text": "You spent ${Value}% of your bill on heating, during the last billing cycle. That\u0027s higher than the average user!","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_220.title -d '[{ "locale": "en_US","text": "Seal your home\u0027s thermal boundary","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_220.shortText -d '[{ "locale": "en_US","text": "Sealing your home’s envelope can save on your energy bill and keep you more comfortable.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_220.longText -d '[{ "locale": "en_US","text": "Sealing your home’s envelope can save on your energy bill and keep you more comfortable.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_SLF_G_SH_001.insightText -d '[{ "locale": "en_US","text": "You spent ${Value}% of your bill on heating, during the last billing cycle. That\u0027s higher than the average user!","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_221.title -d '[{ "locale": "en_US","text": "Adjust humidity levels","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_221.shortText -d '[{ "locale": "en_US","text": "A well-humidified house with plants and aquariums at 68°F is as comfortable as a dry one at 75°F.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_221.longText -d '[{ "locale": "en_US","text": "A well-humidified house with plants and aquariums at 68°F is as comfortable as a dry one at 75°F.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_SLF_G_SH_001.insightText -d '[{ "locale": "en_US","text": "You spent ${Value}% of your bill on heating, during the last billing cycle. That\u0027s higher than the average user!","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_222.title -d '[{ "locale": "en_US","text": "Lower your furnace when using fireplace","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_222.shortText -d '[{ "locale": "en_US","text": "When using the fireplace, turn down the furnace. When not, close the damper to block incoming air.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_222.longText -d '[{ "locale": "en_US","text": "When using the fireplace, turn down the furnace. When not, close the damper to block incoming air.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_SLF_G_SH_001.insightText -d '[{ "locale": "en_US","text": "You spent ${Value}% of your bill on heating, during the last billing cycle. That\u0027s higher than the average user!","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_224.title -d '[{ "locale": "en_US","text": "Let the sun do the work","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_224.shortText -d '[{ "locale": "en_US","text": "During the winter, open curtains on your south-facing windows and let sunlight heat your home.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_224.longText -d '[{ "locale": "en_US","text": "During the winter, open curtains on your south-facing windows and let sunlight heat your home.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_SLF_G_SH_001.insightText -d '[{ "locale": "en_US","text": "You spent ${Value}% of your bill on heating, during the last billing cycle. That\u0027s higher than the average user!","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_225.title -d '[{ "locale": "en_US","text": "Maintain heating system","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_225.shortText -d '[{ "locale": "en_US","text": "Have your furnace serviced yearly and replace the filter regularly to help it run efficiently.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_225.longText -d '[{ "locale": "en_US","text": "Have your furnace serviced yearly and replace the filter regularly to help it run efficiently.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_SLF_G_SH_001.insightText -d '[{ "locale": "en_US","text": "You spent ${Value}% of your bill on heating, during the last billing cycle. That\u0027s higher than the average user!","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_226.title -d '[{ "locale": "en_US","text": "Have your furnace professionally checked","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_226.shortText -d '[{ "locale": "en_US","text": "Have your furnace professionally checked. Annual checks can keep your furnace operating efficiently by spotting and correcting problems.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_226.longText -d '[{ "locale": "en_US","text": "Have your furnace professionally checked. Annual checks can keep your furnace operating efficiently by spotting and correcting problems.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_SLF_G_SH_001.insightText -d '[{ "locale": "en_US","text": "You spent ${Value}% of your bill on heating, during the last billing cycle. That\u0027s higher than the average user!","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_227.title -d '[{ "locale": "en_US","text": "Secure the boiler room against leakage of hazardous gases","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_227.shortText -d '[{ "locale": "en_US","text": "Secure the boiler room against leakage of hazardous gases. Equip the boiler room with a leak detector of natural gas and carbon monoxide.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_227.longText -d '[{ "locale": "en_US","text": "Secure the boiler room against leakage of hazardous gases. Equip the boiler room with a leak detector of natural gas and carbon monoxide.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_SLF_G_SH_001.insightText -d '[{ "locale": "en_US","text": "You spent ${Value}% of your bill on heating, during the last billing cycle. That\u0027s higher than the average user!","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_228.title -d '[{ "locale": "en_US","text": "Foundation plants aid energy efficiency","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_228.shortText -d '[{ "locale": "en_US","text": "Foundation plants aid energy efficiency. Smaller plants minimize loss of cool air during the summer and provide wind protection in the winter.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_228.longText -d '[{ "locale": "en_US","text": "Foundation plants aid energy efficiency. Smaller plants minimize loss of cool air during the summer and provide wind protection in the winter.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_SLF_G_SH_001.insightText -d '[{ "locale": "en_US","text": "You spent ${Value}% of your bill on heating, during the last billing cycle. That\u0027s higher than the average user!","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_229.title -d '[{ "locale": "en_US","text": "Use styrofoam plugs around outlets","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_229.shortText -d '[{ "locale": "en_US","text": "Use styrofoam plugs around outlets. They seal off energy loss around outlet plugs and light switches inside your home.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_229.longText -d '[{ "locale": "en_US","text": "Use styrofoam plugs around outlets. They seal off energy loss around outlet plugs and light switches inside your home.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_SLF_G_SH_001.insightText -d '[{ "locale": "en_US","text": "You spent ${Value}% of your bill on heating, during the last billing cycle. That\u0027s higher than the average user!","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_230.title -d '[{ "locale": "en_US","text": "Cover your window air conditioners","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_230.shortText -d '[{ "locale": "en_US","text": "Keep out winter air by weather-stripping your unit, or covering window ACs tightly on the inside.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_230.longText -d '[{ "locale": "en_US","text": "Keep out winter air by weather-stripping your unit, or covering window ACs tightly on the inside.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_SLF_G_SH_001.insightText -d '[{ "locale": "en_US","text": "You spent ${Value}% of your bill on heating, during the last billing cycle. That\u0027s higher than the average user!","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_231.title -d '[{ "locale": "en_US","text": "Lower your heat by a few degrees","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_231.shortText -d '[{ "locale": "en_US","text": "Lower your heat by a few degrees. Each degree you lower your heat in the 60-70°F degree range can save 2% on your heating costs.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_231.longText -d '[{ "locale": "en_US","text": "Lower your heat by a few degrees. Each degree you lower your heat in the 60-70°F degree range can save 2% on your heating costs.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_SLF_G_SH_001.insightText -d '[{ "locale": "en_US","text": "You spent ${Value}% of your bill on heating, during the last billing cycle. That\u0027s higher than the average user!","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_232.title -d '[{ "locale": "en_US","text": "Upgrade fireplaces","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_232.shortText -d '[{ "locale": "en_US","text": "Upgrade your fireplace. Older fireplaces can pull cold air in along the floor. Newer ones have vents to prevent this.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_232.longText -d '[{ "locale": "en_US","text": "Upgrade your fireplace. Older fireplaces can pull cold air in along the floor. Newer ones have vents to prevent this.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_SLF_G_SH_001.insightText -d '[{ "locale": "en_US","text": "You spent ${Value}% of your bill on heating, during the last billing cycle. That\u0027s higher than the average user!","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_233.title -d '[{ "locale": "en_US","text": "Install insulating shades on windows","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_233.shortText -d '[{ "locale": "en_US","text": "Install insulating drapes or shades to insulate cold windows from your room.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_233.longText -d '[{ "locale": "en_US","text": "Install insulating drapes or shades to insulate cold windows from your room.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_SLF_G_SH_001.insightText -d '[{ "locale": "en_US","text": "You spent ${Value}% of your bill on heating, during the last billing cycle. That\u0027s higher than the average user!","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_234.title -d '[{ "locale": "en_US","text": "Properly seal and insulate","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_234.shortText -d '[{ "locale": "en_US","text": "Properly seal and insulate your home. Adding insulation and sealing gaps and cracks can save more than 30% on home heating costs.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_234.longText -d '[{ "locale": "en_US","text": "Properly seal and insulate your home. Adding insulation and sealing gaps and cracks can save more than 30% on home heating costs.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_SLF_G_SH_001.insightText -d '[{ "locale": "en_US","text": "You spent ${Value}% of your bill on heating, during the last billing cycle. That\u0027s higher than the average user!","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_235.title -d '[{ "locale": "en_US","text": "Seal the gaps!","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_235.shortText -d '[{ "locale": "en_US","text": "Save energy with good seals around drafty doors and windows, and replace weather-stripping.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_235.longText -d '[{ "locale": "en_US","text": "Save energy with good seals around drafty doors and windows, and replace weather-stripping.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_SLF_G_SH_001.insightText -d '[{ "locale": "en_US","text": "You spent ${Value}% of your bill on heating, during the last billing cycle. That\u0027s higher than the average user!","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_237.title -d '[{ "locale": "en_US","text": "Install well-insulated doors & windows","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_237.shortText -d '[{ "locale": "en_US","text": "Install well-insulated doors & windows. Double-glazed and double-paned doors and windows are well-insulated and reduce heat loss.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_237.longText -d '[{ "locale": "en_US","text": "Install well-insulated doors & windows. Double-glazed and double-paned doors and windows are well-insulated and reduce heat loss.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_SLF_G_SH_001.insightText -d '[{ "locale": "en_US","text": "You spent ${Value}% of your bill on heating, during the last billing cycle. That\u0027s higher than the average user!","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_238.title -d '[{ "locale": "en_US","text": "Tightly close fireplace damper","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_238.shortText -d '[{ "locale": "en_US","text": "Ensure your fireplace damper closes tightly when you\u0027re not using it to reduce heat loss.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_238.longText -d '[{ "locale": "en_US","text": "Ensure your fireplace damper closes tightly when you\u0027re not using it to reduce heat loss.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_SLF_G_SH_001.insightText -d '[{ "locale": "en_US","text": "You spent ${Value}% of your bill on heating, during the last billing cycle. That\u0027s higher than the average user!","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_239.title -d '[{ "locale": "en_US","text": "Insulate with shrubbery","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_239.shortText -d '[{ "locale": "en_US","text": "Planting evergreen hedges around your home helps insulate your home. Call 811 before you dig.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_239.longText -d '[{ "locale": "en_US","text": "Planting evergreen hedges around your home helps insulate your home. Call 811 before you dig.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_SLF_G_SH_001.insightText -d '[{ "locale": "en_US","text": "You spent ${Value}% of your bill on heating, during the last billing cycle. That\u0027s higher than the average user!","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_240.title -d '[{ "locale": "en_US","text": "Plant trees that lose leaves in winter","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_240.shortText -d '[{ "locale": "en_US","text": "Plant trees that lose leaves in winter. During winter, this can let sunshine in and warm your home. Call your utility before you dig!","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_240.longText -d '[{ "locale": "en_US","text": "Plant trees that lose leaves in winter. During winter, this can let sunshine in and warm your home. Call your utility before you dig!","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_SLF_G_SH_001.insightText -d '[{ "locale": "en_US","text": "You spent ${Value}% of your bill on heating, during the last billing cycle. That\u0027s higher than the average user!","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_241.title -d '[{ "locale": "en_US","text": "Avoid the night sweats","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_241.shortText -d '[{ "locale": "en_US","text": "Avoid the night sweats. During the winter set your thermostat between 65 and 68°F overnight to reduce heating costs.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_241.longText -d '[{ "locale": "en_US","text": "Avoid the night sweats. During the winter set your thermostat between 65 and 68°F overnight to reduce heating costs.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_SLF_G_SH_001.insightText -d '[{ "locale": "en_US","text": "You spent ${Value}% of your bill on heating, during the last billing cycle. That\u0027s higher than the average user!","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_243.title -d '[{ "locale": "en_US","text": "Close curtains at night","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_243.shortText -d '[{ "locale": "en_US","text": "Close curtains and blinds at night to help keep warm air from escaping in cold weather.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_243.longText -d '[{ "locale": "en_US","text": "Close curtains and blinds at night to help keep warm air from escaping in cold weather.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_SLF_G_SH_001.insightText -d '[{ "locale": "en_US","text": "You spent ${Value}% of your bill on heating, during the last billing cycle. That\u0027s higher than the average user!","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_244.title -d '[{ "locale": "en_US","text": "Insulate your attic or top floor","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_244.shortText -d '[{ "locale": "en_US","text": "Save on your energy costs by better insulating your attic or top floor.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_244.longText -d '[{ "locale": "en_US","text": "Save on your energy costs by better insulating your attic or top floor.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_SLF_G_SH_001.insightText -d '[{ "locale": "en_US","text": "You spent ${Value}% of your bill on heating, during the last billing cycle. That\u0027s higher than the average user!","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_245.title -d '[{ "locale": "en_US","text": "Use ventilating fans sparingly","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_245.shortText -d '[{ "locale": "en_US","text": "Turn off ventillating fans after use.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_245.longText -d '[{ "locale": "en_US","text": "Turn off ventillating fans after use.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_SLF_G_SH_001.insightText -d '[{ "locale": "en_US","text": "You spent ${Value}% of your bill on heating, during the last billing cycle. That\u0027s higher than the average user!","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_246.title -d '[{ "locale": "en_US","text": "Use a draft stopper","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_246.shortText -d '[{ "locale": "en_US","text": "Install a door sweep or draft stopper on your door to help reduce air drafts.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_246.longText -d '[{ "locale": "en_US","text": "Install a door sweep or draft stopper on your door to help reduce air drafts.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_SLF_G_SH_001.insightText -d '[{ "locale": "en_US","text": "You spent ${Value}% of your bill on heating, during the last billing cycle. That\u0027s higher than the average user!","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_247.title -d '[{ "locale": "en_US","text": "Don\u0027t block air ducts and registers","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_247.shortText -d '[{ "locale": "en_US","text": "Move furniture away from air registers and ducts to allow free flow of heated air.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_247.longText -d '[{ "locale": "en_US","text": "Move furniture away from air registers and ducts to allow free flow of heated air.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_SLF_G_SH_001.insightText -d '[{ "locale": "en_US","text": "You spent ${Value}% of your bill on heating, during the last billing cycle. That\u0027s higher than the average user!","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_248.title -d '[{ "locale": "en_US","text": "Shut your fireplace and stove flue","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_248.shortText -d '[{ "locale": "en_US","text": "Wood-burning fireplaces and stoves are known for heat loss. Close the damper when not in use.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_248.longText -d '[{ "locale": "en_US","text": "Wood-burning fireplaces and stoves are known for heat loss. Close the damper when not in use.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_SLF_G_SH_001.insightText -d '[{ "locale": "en_US","text": "You spent ${Value}% of your bill on heating, during the last billing cycle. That\u0027s higher than the average user!","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_249.title -d '[{ "locale": "en_US","text": "Get your furnace inspected before winter","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_249.shortText -d '[{ "locale": "en_US","text": "Avoid the fall rush by having your furnace inspected in late summer or early fall.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_G_SH_249.longText -d '[{ "locale": "en_US","text": "Avoid the fall rush by having your furnace inspected in late summer or early fall.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_SLF_G_SH_001.insightText -d '[{ "locale": "en_US","text": "You spent ${Value}% of your bill on heating, during the last billing cycle. That\u0027s higher than the average user!","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NWN_NBI_PRG_G_G_SH_01.title -d '[{ "locale": "en_US","text": "Free weatherization upgrades: see if you qualify","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NWN_NBI_PRG_G_G_SH_01.shortText -d '[{ "locale": "en_US","text": "Cold last winter? If you are on a limited income, you can receive a new gas furnace, new gas water heater, home insulation, and sealing of air leaks for no charge. Learn more at nwnatural.com/Weatherization","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NWN_NBI_PRG_G_G_SH_01.longText -d '[{ "locale": "en_US","text": "Cold last winter? If you are on a limited income, you can receive a new gas furnace, new gas water heater, home insulation, and sealing of air leaks for no charge. Learn more at nwnatural.com/Weatherization","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_SLF_G_SH_002.insightText -d '[{ "locale": "en_US","text": "You used ${Value}% more energy for Heating in the last billing cycle compared to the same period last year.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NWN_NBI_PRG_G_G_WH_001.title -d '[{ "locale": "en_US","text": "Save on a high-efficiency natural gas tankless water heater upgrade","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NWN_NBI_PRG_G_G_WH_001.shortText -d '[{ "locale": "en_US","text": "Save space & energy and get on-demand hot water by upgrading to a high-efficiency tankless heater. Bonus: It comes with battery backup and works even when the power goes out. Learn more at nwnatural.com/Tankless","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NWN_NBI_PRG_G_G_WH_001.longText -d '[{ "locale": "en_US","text": "Save space & energy and get on-demand hot water by upgrading to a high-efficiency tankless heater. Bonus: It comes with battery backup and works even when the power goes out. Learn more at nwnatural.com/Tankless","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_SLF_G_WH_002.insightText -d '[{ "locale": "en_US","text": "You used ${Value} % more energy for Water Heating in the last billing cycle compared to the same period last year.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NWN_NBI_PRG_G_G_TO_001.title -d '[{ "locale": "en_US","text": "Get Energy Trust incentives when you make home energy-efficiency  improvements","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NWN_NBI_PRG_G_G_TO_001.shortText -d '[{ "locale": "en_US","text": "As a NW Natural customer, you can get Energy Trust cash incentives for making high-efficiency natural gas appliance and weatherization upgrades. Learn more at nwnatural.com/EnergyTrust","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NWN_NBI_PRG_G_G_TO_001.longText -d '[{ "locale": "en_US","text": "As a NW Natural customer, you can get Energy Trust cash incentives for making high-efficiency natural gas appliance and weatherization upgrades. Learn more at nwnatural.com/EnergyTrust","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_EDU_G_YY_001.insightText -d '[{ "locale": "en_US","text": "Your gas bill breakdown is now available and will tell you what uses the most in your home.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NWN_NBI_PRG_G_G_TO_003.title -d '[{ "locale": "en_US","text": "Save on high-efficiency natural gas appliance upgrades and installations","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NWN_NBI_PRG_G_G_TO_003.shortText -d '[{ "locale": "en_US","text": "High-efficiency natural gas appliance upgrades can lower energy bills and improve your comfort at home. Rebates from NW Natural Preferred Contractors can offset the cost. Learn more at nwnatural.com/Offers","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NWN_NBI_PRG_G_G_TO_003.longText -d '[{ "locale": "en_US","text": "High-efficiency natural gas appliance upgrades can lower energy bills and improve your comfort at home. Rebates from NW Natural Preferred Contractors can offset the cost. Learn more at nwnatural.com/Offers","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_EDU_G_YY_001.insightText -d '[{ "locale": "en_US","text": "Your gas bill breakdown is now available and will tell you what uses the most in your home.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NWN_NBI_PRG_G_G_TO_005.title -d '[{ "locale": "en_US","text": "Mitigate carbon emissions from your household natural gas use","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NWN_NBI_PRG_G_G_TO_005.shortText -d '[{ "locale": "en_US","text": "Enroll in Smart Energy and join 84,000+ customers who mitigate the carbon emissions from their natural gas use through a mix of carbon offsets and renewable natural gas projects. Sign up! nwnatural.com/Smart","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NWN_NBI_PRG_G_G_TO_005.longText -d '[{ "locale": "en_US","text": "Enroll in Smart Energy and join 84,000+ customers who mitigate the carbon emissions from their natural gas use through a mix of carbon offsets and renewable natural gas projects. Sign up! nwnatural.com/Smart","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_EDU_G_YY_001.insightText -d '[{ "locale": "en_US","text": "Your gas bill breakdown is now available and will tell you what uses the most in your home.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_SH_01_T-G-S-AC-015.title -d '[{ "locale": "en_US","text": "Shut your flue","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_SH_01_T-G-S-AC-015.shortText -d '[{ "locale": "en_US","text": "Closing the flue on your fireplace can keep cold air from entering through the chimney.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_SH_01_T-G-S-AC-015.longText -d '[{ "locale": "en_US","text": "Closing the flue on your fireplace can keep cold air from entering through the chimney.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_SH_01.insightText -d '[{ "locale": "en_US","text": "Your average monthly energy bill last winter was $${Value} lower than the rest of the year. Keep it up with these tips!","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_SH_01_T-G-S-AC-016.title -d '[{ "locale": "en_US","text": "Shut your flue","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_SH_01_T-G-S-AC-016.shortText -d '[{ "locale": "en_US","text": "Closing the flue on your fireplace can keep cold air from entering through the chimney.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_SH_01_T-G-S-AC-016.longText -d '[{ "locale": "en_US","text": "Closing the flue on your fireplace can keep cold air from entering through the chimney.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_SH_01.insightText -d '[{ "locale": "en_US","text": "Your average monthly energy bill last winter was $${Value} lower than the rest of the year. Keep it up with these tips!","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_SH_01_T-G-S-AC-018.title -d '[{ "locale": "en_US","text": "Shut your flue","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_SH_01_T-G-S-AC-018.shortText -d '[{ "locale": "en_US","text": "Closing the flue on your fireplace can keep cold air from entering through the chimney.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_SH_01_T-G-S-AC-018.longText -d '[{ "locale": "en_US","text": "Closing the flue on your fireplace can keep cold air from entering through the chimney.","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_SH_01.insightText -d '[{ "locale": "en_US","text": "Your average monthly energy bill last winter was $${Value} lower than the rest of the year. Keep it up with these tips!","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_SH_01_T-E-K-SH-001.title -d '[{ "locale": "en_US","text": "Free weatherization upgrades: see if you qualify","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_SH_01_T-E-K-SH-001.shortText -d '[{ "locale": "en_US","text": "Cold last winter? If you are on a limited income, you can receive a new gas furnace, new gas water heater, home insulation, and sealing of air leaks for no charge. Learn more at nwnatural.com/Weatherization","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_SH_01_T-E-K-SH-001.longText -d '[{ "locale": "en_US","text": "Cold last winter? If you are on a limited income, you can receive a new gas furnace, new gas water heater, home insulation, and sealing of air leaks for no charge. Learn more at nwnatural.com/Weatherization","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_EDU_G_SH_003.insightText -d '[{ "locale": "en_US","text": "Did you know? Almost half of the U.S. population with a heating system sets one temperature and leave it there most of the time?","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_SH_01_T-E-K-SH-002.title -d '[{ "locale": "en_US","text": "Free weatherization upgrades: see if you qualify","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_SH_01_T-E-K-SH-002.shortText -d '[{ "locale": "en_US","text": "Cold last winter? If you are on a limited income, you can receive a new gas furnace, new gas water heater, home insulation, and sealing of air leaks for no charge. Learn more at nwnatural.com/Weatherization","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_SH_01_T-E-K-SH-002.longText -d '[{ "locale": "en_US","text": "Cold last winter? If you are on a limited income, you can receive a new gas furnace, new gas water heater, home insulation, and sealing of air leaks for no charge. Learn more at nwnatural.com/Weatherization","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_EDU_G_SH_003.insightText -d '[{ "locale": "en_US","text": "Did you know? Almost half of the U.S. population with a heating system sets one temperature and leave it there most of the time?","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_SH_01_T-E-K-SH-003.title -d '[{ "locale": "en_US","text": "Free weatherization upgrades: see if you qualify","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_SH_01_T-E-K-SH-003.shortText -d '[{ "locale": "en_US","text": "Cold last winter? If you are on a limited income, you can receive a new gas furnace, new gas water heater, home insulation, and sealing of air leaks for no charge. Learn more at nwnatural.com/Weatherization","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_SH_01_T-E-K-SH-003.longText -d '[{ "locale": "en_US","text": "Cold last winter? If you are on a limited income, you can receive a new gas furnace, new gas water heater, home insulation, and sealing of air leaks for no charge. Learn more at nwnatural.com/Weatherization","tags": "her_ui,LP_COMPONENT_HER"}]'`
`curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10037/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_EDU_G_SH_003.insightText -d '[{ "locale": "en_US","text": "Did you know? Almost half of the U.S. population with a heating system sets one temperature and leave it there most of the time?","tags": "her_ui,LP_COMPONENT_HER"}]'`
