 echo `curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10046/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_E_AO_001.title -d '[{ "locale": "en_US","text": "Don\u0027t want to keep unplugging?","tags": "her_ui,LP_COMPONENT_HER"}]'`
 echo `curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10046/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_E_AO_001.shortText -d '[{ "locale": "en_US","text": "Use a Smart Plug! These compact devices allow remote control and scheduling to avoid unnecessary energy use.","tags": "her_ui,LP_COMPONENT_HER"}]'`
 echo `curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10046/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_E_AO_001.longText -d '[{ "locale": "en_US","text": "Use a Smart Plug! These compact devices allow remote control and scheduling to avoid unnecessary energy use.","tags": "her_ui,LP_COMPONENT_HER"}]'`
 echo `curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10046/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_SLF_E_AO_003.insightText -d '[{ "locale": "en_US","text": "You used ${Value}% more energy in Always On devices, in the last billing cycle, compared to the same period last year.","tags": "her_ui,LP_COMPONENT_HER"}]'`
 echo `curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10046/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_E_AO_009.title -d '[{ "locale": "en_US","text": "Use a Smart Power Strip to save electricity automatically!","tags": "her_ui,LP_COMPONENT_HER"}]'`
 echo `curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10046/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_E_AO_009.shortText -d '[{ "locale": "en_US","text": "Using a smart power strip is a simple strategy to reduce your phantom power loads and save money.","tags": "her_ui,LP_COMPONENT_HER"}]'`
 echo `curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10046/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_E_AO_009.longText -d '[{ "locale": "en_US","text": "Using a smart power strip is a simple strategy to reduce your phantom power loads and save money.","tags": "her_ui,LP_COMPONENT_HER"}]'`
 echo `curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10046/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_SLF_E_AO_003.insightText -d '[{ "locale": "en_US","text": "You used ${Value}% more energy in Always On devices, in the last billing cycle, compared to the same period last year.","tags": "her_ui,LP_COMPONENT_HER"}]'`
 echo `curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10046/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_E_AO_013.title -d '[{ "locale": "en_US","text": "Look for ENERGY STAR® rated equipment","tags": "her_ui,LP_COMPONENT_HER"}]'`
 echo `curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10046/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_E_AO_013.shortText -d '[{ "locale": "en_US","text": "ENERGY STAR certified audio visual equipment is up to 70% more efficient than conventional models.","tags": "her_ui,LP_COMPONENT_HER"}]'`
 echo `curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10046/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_E_AO_013.longText -d '[{ "locale": "en_US","text": "ENERGY STAR certified audio visual equipment is up to 70% more efficient than conventional models.","tags": "her_ui,LP_COMPONENT_HER"}]'`
 echo `curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10046/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_SLF_E_AO_003.insightText -d '[{ "locale": "en_US","text": "You used ${Value}% more energy in Always On devices, in the last billing cycle, compared to the same period last year.","tags": "her_ui,LP_COMPONENT_HER"}]'`
 echo `curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10046/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_E_AO_021.title -d '[{ "locale": "en_US","text": "Take the weekend off!","tags": "her_ui,LP_COMPONENT_HER"}]'`
 echo `curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10046/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_E_AO_021.shortText -d '[{ "locale": "en_US","text": "If you have a home office, make sure those appliances are turned off on the weekend and when you\u0027re on vacation.","tags": "her_ui,LP_COMPONENT_HER"}]'`
 echo `curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10046/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_E_AO_021.longText -d '[{ "locale": "en_US","text": "If you have a home office, make sure those appliances are turned off on the weekend and when you\u0027re on vacation.","tags": "her_ui,LP_COMPONENT_HER"}]'`
 echo `curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10046/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_SLF_E_AO_003.insightText -d '[{ "locale": "en_US","text": "You used ${Value}% more energy in Always On devices, in the last billing cycle, compared to the same period last year.","tags": "her_ui,LP_COMPONENT_HER"}]'`
 echo `curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10046/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_E_CK_001.title -d '[{ "locale": "en_US","text": "Use oven lights to check on food","tags": "her_ui,LP_COMPONENT_HER"}]'`
 echo `curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10046/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_E_CK_001.shortText -d '[{ "locale": "en_US","text": "Opening the oven for 10 seconds to check on food could drop the temperature inside by 20°F (12°C).","tags": "her_ui,LP_COMPONENT_HER"}]'`
 echo `curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10046/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_E_CK_001.longText -d '[{ "locale": "en_US","text": "Opening the oven for 10 seconds to check on food could drop the temperature inside by 20°F (12°C).","tags": "her_ui,LP_COMPONENT_HER"}]'`
 echo `curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10046/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_BLL_E_TE_001.insightText -d '[{ "locale": "en_US","text": "We noticed you\u0027ve been using more energy lately. Your last bill increased ${Value}% compared to your previous bill.","tags": "her_ui,LP_COMPONENT_HER"}]'`
 echo `curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10046/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_E_CK_005.title -d '[{ "locale": "en_US","text": "Use an electric kettle","tags": "her_ui,LP_COMPONENT_HER"}]'`
 echo `curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10046/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_E_CK_005.shortText -d '[{ "locale": "en_US","text": "Electric kettles boil water faster than the stovetop and can thus save you money and energy.","tags": "her_ui,LP_COMPONENT_HER"}]'`
 echo `curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10046/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_E_CK_005.longText -d '[{ "locale": "en_US","text": "Electric kettles boil water faster than the stovetop and can thus save you money and energy.","tags": "her_ui,LP_COMPONENT_HER"}]'`
 echo `curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10046/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_BLL_E_TE_001.insightText -d '[{ "locale": "en_US","text": "We noticed you\u0027ve been using more energy lately. Your last bill increased ${Value}% compared to your previous bill.","tags": "her_ui,LP_COMPONENT_HER"}]'`
 echo `curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10046/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_E_CK_009.title -d '[{ "locale": "en_US","text": "Use the right burner","tags": "her_ui,LP_COMPONENT_HER"}]'`
 echo `curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10046/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_E_CK_009.shortText -d '[{ "locale": "en_US","text": "Using the right-sized burner for your pot can speed up your cooking and reduce energy loss by 40%.","tags": "her_ui,LP_COMPONENT_HER"}]'`
 echo `curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10046/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_E_CK_009.longText -d '[{ "locale": "en_US","text": "Using the right-sized burner for your pot can speed up your cooking and reduce energy loss by 40%.","tags": "her_ui,LP_COMPONENT_HER"}]'`
 echo `curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10046/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_BLL_E_TE_001.insightText -d '[{ "locale": "en_US","text": "We noticed you\u0027ve been using more energy lately. Your last bill increased ${Value}% compared to your previous bill.","tags": "her_ui,LP_COMPONENT_HER"}]'`
 echo `curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10046/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_E_CK_013.title -d '[{ "locale": "en_US","text": "Use the right-sized appliance to heat your meals","tags": "her_ui,LP_COMPONENT_HER"}]'`
 echo `curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10046/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_E_CK_013.shortText -d '[{ "locale": "en_US","text": "Small meals call for small appliances. A toaster or convection oven uses one-third to one-half as much energy as a full-sized oven.","tags": "her_ui,LP_COMPONENT_HER"}]'`
 echo `curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10046/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_E_CK_013.longText -d '[{ "locale": "en_US","text": "Small meals call for small appliances. A toaster or convection oven uses one-third to one-half as much energy as a full-sized oven.","tags": "her_ui,LP_COMPONENT_HER"}]'`
 echo `curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10046/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_BLL_E_TE_001.insightText -d '[{ "locale": "en_US","text": "We noticed you\u0027ve been using more energy lately. Your last bill increased ${Value}% compared to your previous bill.","tags": "her_ui,LP_COMPONENT_HER"}]'`
 echo `curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10046/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_E_CK_017.title -d '[{ "locale": "en_US","text": "Consider replacing your old cookware","tags": "her_ui,LP_COMPONENT_HER"}]'`
 echo `curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10046/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_E_CK_017.shortText -d '[{ "locale": "en_US","text": "Flat-bottomed cookware allows for more contact with heating elements. A warped-bottom pot can take 50% more energy to boil the same amount of water!","tags": "her_ui,LP_COMPONENT_HER"}]'`
 echo `curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10046/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_E_CK_017.longText -d '[{ "locale": "en_US","text": "Flat-bottomed cookware allows for more contact with heating elements. A warped-bottom pot can take 50% more energy to boil the same amount of water!","tags": "her_ui,LP_COMPONENT_HER"}]'`
 echo `curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10046/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_BLL_E_TE_001.insightText -d '[{ "locale": "en_US","text": "We noticed you\u0027ve been using more energy lately. Your last bill increased ${Value}% compared to your previous bill.","tags": "her_ui,LP_COMPONENT_HER"}]'`
 echo `curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10046/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_E_CK_021.title -d '[{ "locale": "en_US","text": "Be lazy with your dishes","tags": "her_ui,LP_COMPONENT_HER"}]'`
 echo `curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10046/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_E_CK_021.shortText -d '[{ "locale": "en_US","text": "Wait until you have enough dishes to fill the dishwasher to save on both water and electricity costs.","tags": "her_ui,LP_COMPONENT_HER"}]'`
 echo `curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10046/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_E_CK_021.longText -d '[{ "locale": "en_US","text": "Wait until you have enough dishes to fill the dishwasher to save on both water and electricity costs.","tags": "her_ui,LP_COMPONENT_HER"}]'`
 echo `curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10046/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_BLL_E_TE_001.insightText -d '[{ "locale": "en_US","text": "We noticed you\u0027ve been using more energy lately. Your last bill increased ${Value}% compared to your previous bill.","tags": "her_ui,LP_COMPONENT_HER"}]'`
 echo `curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10046/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_E_CK_025.title -d '[{ "locale": "en_US","text": "Give slow cookers a try!","tags": "her_ui,LP_COMPONENT_HER"}]'`
 echo `curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10046/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_E_CK_025.shortText -d '[{ "locale": "en_US","text": "Slow cookers use much less energy than a regular stovetop for cooking soups or stews.","tags": "her_ui,LP_COMPONENT_HER"}]'`
 echo `curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10046/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_E_CK_025.longText -d '[{ "locale": "en_US","text": "Slow cookers use much less energy than a regular stovetop for cooking soups or stews.","tags": "her_ui,LP_COMPONENT_HER"}]'`
 echo `curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10046/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_BLL_E_TE_001.insightText -d '[{ "locale": "en_US","text": "We noticed you\u0027ve been using more energy lately. Your last bill increased ${Value}% compared to your previous bill.","tags": "her_ui,LP_COMPONENT_HER"}]'`
 echo `curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10046/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_E_AO_025.title -d '[{ "locale": "en_US","text": "Did you know smart power strips can be controlled by your voice or a smartphone app?","tags": "her_ui,LP_COMPONENT_HER"}]'`
 echo `curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10046/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_E_AO_025.shortText -d '[{ "locale": "en_US","text": "Some even have motion sensors! Finding the right one that matches your needs can help you enjoy greater savings and more control in your home!","tags": "her_ui,LP_COMPONENT_HER"}]'`
 echo `curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10046/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_E_AO_025.longText -d '[{ "locale": "en_US","text": "Some even have motion sensors! Finding the right one that matches your needs can help you enjoy greater savings and more control in your home!","tags": "her_ui,LP_COMPONENT_HER"}]'`
 echo `curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10046/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_SLF_E_AO_002.insightText -d '[{ "locale": "en_US","text": "Your Always On (24/7 energy consuming) device usage increased by ${Value}% in the last billing cycle.","tags": "her_ui,LP_COMPONENT_HER"}]'`
 echo `curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10046/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_E_AO_026.title -d '[{ "locale": "en_US","text": "Automate shutdown of unused devices","tags": "her_ui,LP_COMPONENT_HER"}]'`
 echo `curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10046/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_E_AO_026.shortText -d '[{ "locale": "en_US","text": "Advanced power strips have the ability to automatically shut off devices when not in use.","tags": "her_ui,LP_COMPONENT_HER"}]'`
 echo `curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10046/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_NBI_EE_A_E_AO_026.longText -d '[{ "locale": "en_US","text": "Advanced power strips have the ability to automatically shut off devices when not in use.","tags": "her_ui,LP_COMPONENT_HER"}]'`
 echo `curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10046/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_SLF_E_AO_002.insightText -d '[{ "locale": "en_US","text": "Your Always On (24/7 energy consuming) device usage increased by ${Value}% in the last billing cycle.","tags": "her_ui,LP_COMPONENT_HER"}]'`
 echo `curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10046/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_AC_01_T-E-S-AC-001.title -d '[{ "locale": "en_US","text": "Unblock your vents","tags": "her_ui,LP_COMPONENT_HER"}]'`
 echo `curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10046/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_AC_01_T-E-S-AC-001.shortText -d '[{ "locale": "en_US","text": "Blocked air vents reduce airflow in the cooling system. Make sure your vents are clear of furniture or other obstructions.","tags": "her_ui,LP_COMPONENT_HER"}]'`
 echo `curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10046/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_AC_01_T-E-S-AC-001.longText -d '[{ "locale": "en_US","text": "Blocked air vents reduce airflow in the cooling system. Make sure your vents are clear of furniture or other obstructions.","tags": "her_ui,LP_COMPONENT_HER"}]'`
 echo `curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10046/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_AC_01.insightText -d '[{ "locale": "en_US","text": "During the last 12 months, you used a total of ${Value} kWh for Cooling.","tags": "her_ui,LP_COMPONENT_HER"}]'`
 echo `curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10046/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_AC_01_T-E-S-AC-002.title -d '[{ "locale": "en_US","text": "Unblock your vents","tags": "her_ui,LP_COMPONENT_HER"}]'`
 echo `curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10046/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_AC_01_T-E-S-AC-002.shortText -d '[{ "locale": "en_US","text": "Blocked air vents reduce airflow in the cooling system. Make sure your vents are clear of furniture or other obstructions.","tags": "her_ui,LP_COMPONENT_HER"}]'`
 echo `curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10046/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_AC_01_T-E-S-AC-002.longText -d '[{ "locale": "en_US","text": "Blocked air vents reduce airflow in the cooling system. Make sure your vents are clear of furniture or other obstructions.","tags": "her_ui,LP_COMPONENT_HER"}]'`
 echo `curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10046/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_AC_01.insightText -d '[{ "locale": "en_US","text": "During the last 12 months, you used a total of ${Value} kWh for Cooling.","tags": "her_ui,LP_COMPONENT_HER"}]'`
 echo `curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10046/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_AC_01_T-E-S-AC-003.title -d '[{ "locale": "en_US","text": "Unblock your vents","tags": "her_ui,LP_COMPONENT_HER"}]'`
 echo `curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10046/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_AC_01_T-E-S-AC-003.shortText -d '[{ "locale": "en_US","text": "Blocked air vents reduce airflow in the cooling system. Make sure your vents are clear of furniture or other obstructions.","tags": "her_ui,LP_COMPONENT_HER"}]'`
 echo `curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10046/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_AC_01_T-E-S-AC-003.longText -d '[{ "locale": "en_US","text": "Blocked air vents reduce airflow in the cooling system. Make sure your vents are clear of furniture or other obstructions.","tags": "her_ui,LP_COMPONENT_HER"}]'`
 echo `curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10046/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_AC_01.insightText -d '[{ "locale": "en_US","text": "During the last 12 months, you used a total of ${Value} kWh for Cooling.","tags": "her_ui,LP_COMPONENT_HER"}]'`
 echo `curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10046/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_SH_01_T-E-N-AC-001.title -d '[{ "locale": "en_US","text": "Mitigate carbon emissions from your household natural gas use","tags": "her_ui,LP_COMPONENT_HER"}]'`
 echo `curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10046/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_SH_01_T-E-N-AC-001.shortText -d '[{ "locale": "en_US","text": "Enroll in Smart Energy and join 84,000+ customers who mitigate the carbon emissions from their natural gas use through a mix of carbon offsets and renewable natural gas projects. Sign up! nwnatural.com/Smart","tags": "her_ui,LP_COMPONENT_HER"}]'`
 echo `curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10046/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_SH_01_T-E-N-AC-001.longText -d '[{ "locale": "en_US","text": "Enroll in Smart Energy and join 84,000+ customers who mitigate the carbon emissions from their natural gas use through a mix of carbon offsets and renewable natural gas projects. Sign up! nwnatural.com/Smart","tags": "her_ui,LP_COMPONENT_HER"}]'`
 echo `curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10046/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_EDU_G_YY_002.insightText -d '[{ "locale": "en_US","text": "Whether your bill went up or down, your bill analysis would show you exactly where things changed.","tags": "her_ui,LP_COMPONENT_HER"}]'`
 echo `curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10046/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_SH_01_T-E-N-AC-002.title -d '[{ "locale": "en_US","text": "Mitigate carbon emissions from your household natural gas use","tags": "her_ui,LP_COMPONENT_HER"}]'`
 echo `curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10046/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_SH_01_T-E-N-AC-002.shortText -d '[{ "locale": "en_US","text": "Enroll in Smart Energy and join 84,000+ customers who mitigate the carbon emissions from their natural gas use through a mix of carbon offsets and renewable natural gas projects. Sign up! nwnatural.com/Smart","tags": "her_ui,LP_COMPONENT_HER"}]'`
 echo `curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10046/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_SH_01_T-E-N-AC-002.longText -d '[{ "locale": "en_US","text": "Enroll in Smart Energy and join 84,000+ customers who mitigate the carbon emissions from their natural gas use through a mix of carbon offsets and renewable natural gas projects. Sign up! nwnatural.com/Smart","tags": "her_ui,LP_COMPONENT_HER"}]'`
 echo `curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10046/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_EDU_G_YY_002.insightText -d '[{ "locale": "en_US","text": "Whether your bill went up or down, your bill analysis would show you exactly where things changed.","tags": "her_ui,LP_COMPONENT_HER"}]'`
 echo `curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10046/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_SH_01_T-E-N-AC-003.title -d '[{ "locale": "en_US","text": "Mitigate carbon emissions from your household natural gas use","tags": "her_ui,LP_COMPONENT_HER"}]'`
 echo `curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10046/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_SH_01_T-E-N-AC-003.shortText -d '[{ "locale": "en_US","text": "Enroll in Smart Energy and join 84,000+ customers who mitigate the carbon emissions from their natural gas use through a mix of carbon offsets and renewable natural gas projects. Sign up! nwnatural.com/Smart","tags": "her_ui,LP_COMPONENT_HER"}]'`
 echo `curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10046/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_SH_01_T-E-N-AC-003.longText -d '[{ "locale": "en_US","text": "Enroll in Smart Energy and join 84,000+ customers who mitigate the carbon emissions from their natural gas use through a mix of carbon offsets and renewable natural gas projects. Sign up! nwnatural.com/Smart","tags": "her_ui,LP_COMPONENT_HER"}]'`
 echo `curl -X PUT -H "Authorization: Bearer $2" -H "Content-Type: application/json" $1/2.1/stringResources/10046/resource/com.bidgely.cloud.core.lib.paper.nbi.MOCK_I_EDU_G_YY_002.insightText -d '[{ "locale": "en_US","text": "Whether your bill went up or down, your bill analysis would show you exactly where things changed.","tags": "her_ui,LP_COMPONENT_HER"}]'`
